export const GET_FEED_POSTS_LOADING = 'GET_FEED_POSTS_LOADING';
export const GET_FEED_POSTS_SUCCESS = 'GET_FEED_POSTS_SUCCESS';
export const GET_FEED_POSTS_FAILED = 'GET_FEED_POSTS_FAILED';
export const POST_LIKED = 'POST_LIKED';
export const POST_UNLIKED = 'POST_UNLIKED';
